#pragma once

#include <d3d12.h>

D3D12_RESOURCE_DESC CD3DX12_RESOURCE_DESC_BUFFER(const UINT64 width, const D3D12_RESOURCE_FLAGS flags, const UINT64 alignment);
D3D12_RASTERIZER_DESC CD3DX12_DEFAULT_RASTERIZER_DESC(void);
D3D12_BLEND_DESC CD3DX12_DEFAULT_BLEND_DESC(void);
